version: '3.7'

services:
  fancontrol:
    image: .
    volumes:
    - /sys/class/thermal/thermal_zone0:/sys/class/thermal/thermal_zone0
    - /opt/fancontrol:/app
    entrypoint: python3 fanonoff.py
    restart: unless-stopped